create table if not exists public.news_items (
  id bigint generated by default as identity primary key,
  source text not null,
  source_id text,
  market text not null default 'KR',
  stock_code text,
  stock_name text,
  category text not null default 'company',
  title text not null,
  description text,
  article_url text not null,
  original_url text,
  published_at timestamptz,
  collected_at timestamptz not null default now(),
  is_macro boolean not null default false,
  is_investor_relevant boolean not null default true,
  event_type text,
  filter_reason text,
  metadata jsonb not null default '{}'::jsonb,
  constraint news_items_source_id_unique unique (source, source_id)
);

create index if not exists news_items_market_published_idx
  on public.news_items (market, published_at desc);

create index if not exists news_items_stock_published_idx
  on public.news_items (stock_code, published_at desc);

create index if not exists news_items_macro_published_idx
  on public.news_items (is_macro, published_at desc)
  where is_macro = true;

alter table public.news_items enable row level security;
revoke all on table public.news_items from anon, authenticated;
grant select on table public.news_items to anon, authenticated;

drop policy if exists "Public can read news items" on public.news_items;
create policy "Public can read news items"
  on public.news_items
  for select
  to anon, authenticated
  using (true);

create table if not exists public.earnings_events (
  id bigint generated by default as identity primary key,
  market text not null default 'KR',
  stock_code text,
  stock_name text not null,
  event_date date not null,
  event_type text not null,
  report_name text not null,
  receipt_no text,
  source_url text not null,
  announced_at timestamptz,
  collected_at timestamptz not null default now(),
  is_primary_event boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  constraint earnings_events_receipt_unique unique (market, receipt_no)
);

create index if not exists earnings_events_date_idx
  on public.earnings_events (market, event_date asc);

create index if not exists earnings_events_stock_date_idx
  on public.earnings_events (stock_code, event_date asc);

create index if not exists earnings_events_primary_date_idx
  on public.earnings_events (market, event_date asc)
  where is_primary_event = true;

alter table public.earnings_events enable row level security;
revoke all on table public.earnings_events from anon, authenticated;
grant select on table public.earnings_events to anon, authenticated;

drop policy if exists "Public can read earnings events" on public.earnings_events;
create policy "Public can read earnings events"
  on public.earnings_events
  for select
  to anon, authenticated
  using (true);
